# Generated by Django 5.0.14 on 2026-01-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecentViewProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "danawa_product_id",
                    models.CharField(
                        help_text="다나와 상품 고유 번호",
                        max_length=15,
                        verbose_name="상품 고유 번호",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적 삭제 플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "Recent View Product",
                "verbose_name_plural": "Recent View Products",
                "db_table": "recent_view_products",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField(verbose_name="검색어")),
                (
                    "search_mode",
                    models.CharField(
                        choices=[
                            ("basic", "기본"),
                            ("llm", "LLM"),
                            ("shopping_research", "쇼핑 리서치"),
                        ],
                        help_text="기본/LLM/쇼핑 리서치",
                        max_length=20,
                        verbose_name="검색 모드",
                    ),
                ),
                ("searched_at", models.DateTimeField(verbose_name="검색 일시")),
                (
                    "danawa_product_id",
                    models.CharField(
                        help_text="다나와 상품 고유 번호",
                        max_length=15,
                        verbose_name="상품번호",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "Search",
                "verbose_name_plural": "Searches",
                "db_table": "search",
                "ordering": ["-searched_at"],
            },
        ),
    ]
