# Generated by Django 5.0.14 on 2026-01-17 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("search", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recentviewproductmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recent_view_products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원번호",
            ),
        ),
        migrations.AddField(
            model_name="searchmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="searches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원번호",
            ),
        ),
        migrations.AddIndex(
            model_name="recentviewproductmodel",
            index=models.Index(
                fields=["user", "updated_at"], name="recent_view_user_id_3414e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recentviewproductmodel",
            index=models.Index(
                fields=["danawa_product_id"], name="recent_view_danawa__e8e129_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchmodel",
            index=models.Index(
                fields=["user", "searched_at"], name="search_user_id_6e9231_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchmodel",
            index=models.Index(
                fields=["danawa_product_id"], name="search_danawa__75c56a_idx"
            ),
        ),
    ]
