# Generated by Django 5.0.14 on 2026-01-17 17:52

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "danawa_product_id",
                    models.CharField(
                        db_index=True,
                        help_text="다나와 상품 고유 번호(가격변동 값 API 사용시 필요)",
                        max_length=15,
                        unique=True,
                        verbose_name="상품 고유 번호",
                    ),
                ),
                ("lowest_price", models.IntegerField(verbose_name="최저가")),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="상품명"
                    ),
                ),
                (
                    "detail_spec",
                    models.JSONField(default=dict, verbose_name="상세 스펙"),
                ),
                (
                    "detail_spec_vector",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        null=True,
                        verbose_name="상세 스펙 벡터",
                    ),
                ),
                (
                    "brand",
                    models.CharField(max_length=50, verbose_name="제조사/브랜드"),
                ),
                (
                    "registration_month",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="등록월"
                    ),
                ),
                (
                    "product_status",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="상품상태"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="categories.categorymodel",
                        verbose_name="카테고리번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MallInformationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_price", models.IntegerField(verbose_name="현재가")),
                ("mall_name", models.CharField(max_length=50, verbose_name="판매처명")),
                (
                    "product_page_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="판매페이지 URL",
                    ),
                ),
                (
                    "seller_logo_url",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="판매자 로고",
                    ),
                ),
                (
                    "product_description_image_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="제품설명이미지 URL"
                    ),
                ),
                (
                    "detail_page_image_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="상세페이지 이미지 URL"
                    ),
                ),
                (
                    "additional_image_urls",
                    models.JSONField(
                        blank=True, default=list, verbose_name="추가이미지 URL 목록"
                    ),
                ),
                (
                    "representative_image_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="대표이미지URL",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mall_information",
                        to="products.productmodel",
                        verbose_name="상품번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mall Information",
                "verbose_name_plural": "Mall Information",
                "db_table": "mall_information",
                "ordering": ["current_price"],
            },
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["category"], name="products_categor_4083ff_idx"),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["name"], name="products_name_6f9890_idx"),
        ),
        migrations.AddIndex(
            model_name="productmodel",
            index=models.Index(fields=["brand"], name="products_brand_b2547a_idx"),
        ),
        migrations.AddIndex(
            model_name="mallinformationmodel",
            index=models.Index(
                fields=["product", "mall_name"], name="mall_inform_product_7be261_idx"
            ),
        ),
    ]
