# Generated by Django 5.0.14 on 2026-01-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="review_count",
            field=models.IntegerField(default=0, verbose_name="리뷰 수"),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="review_rating",
            field=models.FloatField(blank=True, null=True, verbose_name="평균 별점"),
        ),
    ]
