# Generated by Django 5.0.14 on 2026-01-20 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_add_hnsw_gin_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAIReviewAnalysisModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_review_summary",
                    models.TextField(
                        blank=True,
                        help_text="해당 상품의 전체 리뷰를 종합한 AI 요약",
                        null=True,
                        verbose_name="AI 리뷰 요약",
                    ),
                ),
                (
                    "ai_positive_review_analysis",
                    models.JSONField(
                        blank=True,
                        help_text="긍정적인 리뷰 포인트 분석 결과",
                        null=True,
                        verbose_name="AI 긍정 리뷰 분석",
                    ),
                ),
                (
                    "ai_negative_review_analysis",
                    models.JSONField(
                        blank=True,
                        help_text="부정적인 리뷰 포인트 분석 결과",
                        null=True,
                        verbose_name="AI 부정 리뷰 분석",
                    ),
                ),
                (
                    "ai_recommendation_score",
                    models.IntegerField(
                        blank=True,
                        help_text="0~100점 구매 추천 점수",
                        null=True,
                        verbose_name="AI 추천점수",
                    ),
                ),
                (
                    "ai_review_analysis_basis",
                    models.TextField(
                        blank=True,
                        help_text="AI가 분석에 사용한 근거 및 참고 리뷰",
                        null=True,
                        verbose_name="AI 리뷰 분석 근거",
                    ),
                ),
                (
                    "analyzed_review_count",
                    models.IntegerField(
                        default=0,
                        help_text="AI 분석에 사용된 리뷰 개수",
                        verbose_name="분석된 리뷰 수",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        db_column="danawa_product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_review_analysis",
                        to="products.productmodel",
                        to_field="danawa_product_id",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product AI Review Analysis",
                "verbose_name_plural": "Product AI Review Analyses",
                "db_table": "product_ai_review_analysis",
                "ordering": ["-updated_at"],
            },
        ),
    ]
