# Generated by Django 5.0.14 on 2026-01-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="이메일",
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="비밀번호")),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                (
                    "nickname",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="닉네임"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "token_balance",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="보유토큰"
                    ),
                ),
                (
                    "social_provider",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="소셜제공자"
                    ),
                ),
                (
                    "social_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="소셜ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
    ]
