# Generated by Django 5.0.14 on 2026-01-20 04:41

from django.db import migrations, models


def calculate_levels(apps, schema_editor):
    """기존 카테고리의 level 값을 계산하여 업데이트."""
    CategoryModel = apps.get_model('categories', 'CategoryModel')

    def get_level(category, cache={}):
        if category.id in cache:
            return cache[category.id]

        if category.parent_id is None:
            cache[category.id] = 0
            return 0

        parent = CategoryModel.objects.get(id=category.parent_id)
        level = get_level(parent, cache) + 1
        cache[category.id] = level
        return level

    cache = {}
    for category in CategoryModel.objects.all():
        level = get_level(category, cache)
        CategoryModel.objects.filter(id=category.id).update(level=level)


def reverse_calculate_levels(apps, schema_editor):
    """Reverse migration: reset all levels to 0."""
    CategoryModel = apps.get_model('categories', 'CategoryModel')
    CategoryModel.objects.all().update(level=0)


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="level",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=0,
                help_text="0=대분류, 1=중분류, 2=소분류, 3=세분류",
                verbose_name="카테고리 레벨",
            ),
        ),
        migrations.RunPython(calculate_levels, reverse_calculate_levels),
    ]
