# Generated by Django 5.0.14 on 2026-01-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_price", models.IntegerField(verbose_name="목표가")),
                (
                    "predicted_price",
                    models.IntegerField(blank=True, null=True, verbose_name="예측가격"),
                ),
                (
                    "prediction_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="예측일자"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="0.00~1.00 범위의 값",
                        null=True,
                        verbose_name="구매 신뢰도",
                    ),
                ),
                (
                    "purchase_suitability_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="구매 적합도 점수"
                    ),
                ),
                (
                    "purchase_guide_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="구매 가이드 메시지"
                    ),
                ),
                (
                    "is_notification_enabled",
                    models.BooleanField(
                        default=True, verbose_name="구매 알림 활성화 여부"
                    ),
                ),
                (
                    "danawa_product_id",
                    models.CharField(
                        help_text="다나와 상품 고유 번호",
                        max_length=15,
                        verbose_name="상품 고유 번호",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "Timer",
                "verbose_name_plural": "Timers",
                "db_table": "timers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="기록일시"
                    ),
                ),
                (
                    "lowest_price",
                    models.IntegerField(blank=True, null=True, verbose_name="최저가"),
                ),
                (
                    "danawa_product_id",
                    models.CharField(
                        help_text="다나와 상품 고유 번호",
                        max_length=15,
                        verbose_name="상품 고유 번호",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price Histories",
                "db_table": "price_histories",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["danawa_product_id", "recorded_at"],
                        name="price_histo_danawa__e45483_idx",
                    )
                ],
            },
        ),
    ]
