# Generated by Django 5.0.14 on 2026-01-17 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("timers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="timermodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원번호",
            ),
        ),
        migrations.AddIndex(
            model_name="timermodel",
            index=models.Index(
                fields=["danawa_product_id", "prediction_date"],
                name="timers_danawa__652533_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timermodel",
            index=models.Index(
                fields=["user", "created_at"], name="timers_user_id_e66928_idx"
            ),
        ),
    ]
