# Generated by Django 5.0.14 on 2026-01-17 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
                "db_table": "carts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderHistoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("charge", "충전"), ("payment", "결제")],
                        help_text="충전/결제",
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                (
                    "token_change",
                    models.IntegerField(
                        help_text="충전은+/결제는-", verbose_name="변동된 토큰양"
                    ),
                ),
                (
                    "token_balance_after",
                    models.IntegerField(
                        help_text="0보다 커야 함", verbose_name="잔액 토큰양"
                    ),
                ),
                ("transaction_at", models.DateTimeField(verbose_name="거래일시")),
                (
                    "danawa_product_id",
                    models.CharField(
                        help_text="다나와 상품 고유 번호",
                        max_length=15,
                        verbose_name="상품번호",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="수정시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "Order History",
                "verbose_name_plural": "Order Histories",
                "db_table": "order_histories",
                "ordering": ["-transaction_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "danawa_product_id",
                    models.CharField(
                        help_text="다나와 상품 고유 번호",
                        max_length=15,
                        verbose_name="상품 고유 번호",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="수량")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "db_table": "order_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mall_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="리뷰 쇼핑몰명",
                    ),
                ),
                (
                    "reviewer_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="리뷰 작성자"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="내용"),
                ),
                (
                    "rating",
                    models.IntegerField(blank=True, null=True, verbose_name="평점"),
                ),
                (
                    "ai_review_summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="AI 리뷰 요약"
                    ),
                ),
                (
                    "ai_positive_review_analysis",
                    models.JSONField(
                        blank=True, null=True, verbose_name="AI 긍정 리뷰 분석"
                    ),
                ),
                (
                    "ai_negative_review_analysis",
                    models.JSONField(
                        blank=True, null=True, verbose_name="AI 부정 리뷰 분석"
                    ),
                ),
                (
                    "ai_recommendation_score",
                    models.IntegerField(
                        blank=True,
                        help_text="0~100점 구매 추천 점수",
                        null=True,
                        verbose_name="AI 추천점수",
                    ),
                ),
                (
                    "ai_review_analysis_basis",
                    models.TextField(
                        blank=True, null=True, verbose_name="AI 리뷰 분석 근거"
                    ),
                ),
                (
                    "review_images",
                    models.JSONField(blank=True, null=True, verbose_name="리뷰 이미지"),
                ),
                (
                    "external_review_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="외부 쇼핑몰 리뷰 총합"
                    ),
                ),
                (
                    "danawa_product_id",
                    models.CharField(
                        help_text="다나와 상품 고유 번호",
                        max_length=15,
                        verbose_name="상품 고유 번호",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="수량")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="products.productmodel",
                        verbose_name="상품번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
                "db_table": "cart_items",
                "ordering": ["-created_at"],
            },
        ),
    ]
