# Generated by Django 5.0.14 on 2026-01-17 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cartmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원번호",
            ),
        ),
        migrations.AddField(
            model_name="cartitemmodel",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.cartmodel",
                verbose_name="장바구니번호",
            ),
        ),
        migrations.AddField(
            model_name="orderhistorymodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_histories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원번호",
            ),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원번호",
            ),
        ),
        migrations.AddField(
            model_name="orderitemmodel",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.ordermodel",
                verbose_name="구매번호",
            ),
        ),
        migrations.AddField(
            model_name="reviewmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원번호",
            ),
        ),
        migrations.AddIndex(
            model_name="orderhistorymodel",
            index=models.Index(
                fields=["user", "transaction_at"], name="order_histo_user_id_be92cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewmodel",
            index=models.Index(
                fields=["danawa_product_id", "created_at"],
                name="reviews_danawa__439902_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewmodel",
            index=models.Index(
                fields=["user", "created_at"], name="reviews_user_id_fc2a09_idx"
            ),
        ),
    ]
