# Generated by Django 5.0.14 on 2026-01-18 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderhistorymodel",
            options={
                "ordering": ["-transaction_at"],
                "verbose_name": "token History",
                "verbose_name_plural": "token Histories",
            },
        ),
        migrations.RenameIndex(
            model_name="orderhistorymodel",
            new_name="token_histo_token_o_4e873d_idx",
            old_name="order_histo_user_id_be92cd_idx",
        ),
        migrations.AlterField(
            model_name="orderhistorymodel",
            name="user",
            field=models.ForeignKey(
                db_column="token_owner_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_histories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원번호",
            ),
        ),
        migrations.AlterModelTable(
            name="orderhistorymodel",
            table="token_histories",
        ),
    ]
