# Generated by Django 5.0.14 on 2026-01-27 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_cart_item_danawa_product_id"),
        ("products", "0004_add_product_ai_review_analysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitemmodel",
            name="product",
            field=models.ForeignKey(
                db_column="danawa_product_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="products.productmodel",
                to_field="danawa_product_id",
                verbose_name="상품번호",
            ),
        ),
    ]
